apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: myapp
        image: myapp
        command: ["node",  "./index-for-job.js"]
        env:
        - name: MY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: key
      restartPolicy: Never
