apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- job.yaml
- deployment.yaml

images:
- name: myapp
  newName: ghcr.io/argentinaluiz/argocd-syncwave
  newTag: v0.0.3
